import { BlogArticle } from './article.model';

export const INITIAL_ARTICLES: BlogArticle[] = [
  {
    id: 1,
    title: 'Как я начал изучать iOS-разработку и прошёл интенсив ШИФТ',
    text: 'Расскажу о своём опыте прохождения интенсива ШИФТ в ЦФТ: как проходило обучение, что изучали и что получилось в итоге.',
    dateLabel: 'Jan 10, 2025',
    isoDate: '2025-01-10',
    tag: 'iOS',
    theme: 'red',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 2,
    title: 'Git для начинающих: основные команды',
    text: '',
    dateLabel: 'Feb 5, 2025',
    isoDate: '2025-02-05',
    tag: 'Git',
    theme: 'green',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 3,
    title: 'Первые шаги в HTML: структура страницы',
    text: '',
    dateLabel: 'Mar 1, 2025',
    isoDate: '2025-03-01',
    tag: 'HTML',
    theme: 'neutral',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 4,
    title: 'Семантические теги HTML: зачем они нужны',
    text: '',
    dateLabel: 'Mar 5, 2025',
    isoDate: '2025-03-05',
    tag: 'HTML',
    theme: 'neutral',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 5,
    title: 'Aurora OS: опыт бета-тестирования',
    text: '',
    dateLabel: 'Mar 8, 2025',
    isoDate: '2025-03-08',
    tag: 'Aurora',
    theme: 'neutral',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 6,
    title: 'CSS Flexbox: как выравнивать элементы',
    text: '',
    dateLabel: 'Mar 10, 2025',
    isoDate: '2025-03-10',
    tag: 'CSS',
    theme: 'green',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
  {
    id: 7,
    title: 'CSS Grid: сетки для вёрстки',
    text: '',
    dateLabel: 'Mar 15, 2025',
    isoDate: '2025-03-15',
    tag: 'CSS',
    theme: 'green',
    image: 'images/Selection.png',
    isUserCreated: false,
  },
];
